# Generated by Django 4.2.7 on 2023-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('required_qualifications', models.TextField(blank=True, null=True)),
                ('desired_qualifications', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=50, null=True)),
                ('company_benefits', models.TextField(blank=True, null=True)),
                ('how_to_apply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
